apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-keycloak
spec:
  type: oci
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 24.7.5
      sourceRef:
        kind: HelmRepository
        name: don-auth-repo-keycloak
  values:
    replicaCount: 1
    production: false
    auth:
      existingSecret: don-auth-keycloak-login-secret
    postgresql:
      enabled: false
      externalDatabase:
        password: ignored-but-required
        existingSecret: don-auth-keycloak-login-secret
        existingSecretHostKey: db-host
        existingSecretUserKey: db-user
        existingSecretDatabaseKey: db-name
        existingSecretPasswordKey: db-password
    extraEnvVars:
      - name: KEYCLOAK_JDBC_PARAMS
        value: "sslmode=require&currentSchema=don_auth"
      # - name: KC_LOG_LEVEL
      #   value: debug
      # - name: KC_DB
      #   value: 'postgres'
      # - name: KEYCLOAK_DATABASE_USER
      #   valueFrom:
      #     secretKeyRef:
      #       name: don-auth-keycloak-login-secret
      #       key: db-user
      # - name: KEYCLOAK_DATABASE_PASSWORD
      #   valueFrom:
      #     secretKeyRef:
      #       name: don-auth-keycloak-login-secret
      #       key: db-password
      # - name: KC_DB_URL
      #   valueFrom:
      #     secretKeyRef:
      #       name: don-auth-keycloak-login-secret
      #       key: KC_DB_URL
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hostname: set-in-overlay
      extraTls:
        - hosts:
            - set-in-overlay
          secretName: auth-tls
    service:
      type: ClusterIP
    podAnnotations: {}
    podLabels: {}
#    extraStartupArgs: "--import-realm"
#
#    extraVolumes:
#      - name: realm-config
#        configMap:
#          name: don-auth-keycloak-realm-config
#    extraVolumeMounts:
#      - name: realm-config
#        mountPath: /opt/bitnami/keycloak/data/import
#        readOnly: true

Helm upgrade failed for release tn-don-auth/don-auth-keycloak with chart keycloak@24.7.5: execution error at (keycloak/templates/secret-external-db.yaml:18:18): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release. Note that even after reinstallation, old credentials 
may be needed as they may be kept in persistent volume claims. Further information can be obtained at 
https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases 
'externalDatabase.password' must not be empty, please add '--set externalDatabase.password=$DB_PASSWORD' to the command. 
To get the current value: export DB_PASSWORD=$(kubectl get secret --namespace "tn-don-auth" don-auth-keycloak-externaldb -o 
jsonpath="{.data.db-password}" | base64 -d) Last Helm logs: 2025-07-16T12:33:13.569886747Z: preparing upgrade for 
don-auth-keycloak 2025-07-16T12:33:13.637218688Z: resetting values to the chart's original version

