apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: don
      owner: don
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  instances: 1
  storage:
    size: 2Gi
