apiVersion: v1
data:
    API_BASEURL: ENC[AES256_GCM,data:uUrop0el0Kcu701qeeYff8Q0X2kVBL43Pt4AWgF8R4wxG3raFy8wrJ14qav3RO9dD1MCuAfSxYB8EVP5c7g+0vsSbNg=,iv:v1GvjWRpR/VR7/EBc1d0hNsxE8dwjYulDS5XCPBbBsU=,tag:PaZyWlRYQjwfHWstp9M9ig==,type:str]
    API_X_API_KEY: ENC[AES256_GCM,data:tvgEN1M8AoCplodqS5S/5NdgKJ0ai5envuoacQcai+9twL97ra12lsdl+ML5n1AX,iv:XyRONRrEpKVv23yXp2+tSgMoFR7pnhAltef4s8ehyDI=,tag:gb+G0uLht6k4v6Jez1FO0g==,type:str]
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:yfJyZ+KpVJEz1gQgnWZDE6wEz8puufUl,iv:QoYAkGdRzR5IlphTN8uYJbaP+YBwLmVvM3/oitNBozw=,tag:mcaKc6LJBEfWnu8XGEA+aA==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:hrIhlJ2stJYMApU8/+5Ph5J6XfWKW9LHfpGcEH/ZwqUA/ZpTdaKKuVTh110=,iv:vzf0tyDTgEuskGWMHKTyRoQrh7xEkFVLwWRmcAnmXpA=,tag:UidsMeP00pwN8Auzyk3T2Q==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:Ua3sv2CLUv7j4pGor5yCnzLYFFbdV3NnONWLZof2YXcJ9QNtPibE/kUOSP7ZNGdEfh1dJxVvK/4=,iv:IaeZZANupMHJrdRMxghk/uGFHanR903UGs99s6CxuKM=,tag:XQ+LO8b1DpBROS1YEVSJeQ==,type:str]
    GITLAB_TOKEN: ENC[AES256_GCM,data:BqXRK80F5ClqUnJqqV8lUiEknXPvgdx5u9Pl1woUHsXKueDNF/DNqugGPHBs/MigMcAl+PjYlJTeS8DAoT1pVmOlqkfE+zVg29mdzg==,iv:9hsPdVJ0ctaFEpX40r2F4tMrMqnX6c1INh3XpscZpRc=,tag:yzQZ/IRiZc10x9qLYBvwQQ==,type:str]
    KEYCLOAK_BASE_URL: ENC[AES256_GCM,data:6GYeso9/NUakZ47Tduk73VcNru4JDsB63I3EGEn7VsA39YwFlx2co1w0A11/T75J,iv:cvWoK4o13gyeZjw89AZhg6kQdnhc7bnTeIcuNtyuxIQ=,tag:57a1KhlAnwyFPyRLhQeFjA==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:VNk51g==,iv:W57TkcARaev7pEeZKkb8ipFRCTr1Aw6lth2Xzi7/CMs=,tag:gC1E1C3wJZKdnwJPRaUOKA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: don-crawler-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g59lru89pjncetzrnlr23cc4vq6rct5npsc9xcf89v26slm6g5msh579ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc2xORHpoc1YxZno2TUtD
            akc3YktvWWdPUDU2MGJyNi9GcWRwbk9aZHdZCmhWaHZIQnZtSzhFN2puTnFwYkRa
            ZGgvWXZLeVNTRW9PWU5QTXA3WmdSVFkKLS0tIEI0Z3NCaDBjaUhGU0IwTWIzc1Zn
            SEkxWkM4cldxY29CRGlMcGp1Nmxna3cKYoaGOLuM9Q+xBttqAh+dZlW3g2B5RywY
            +2w2gXiicjJnygHgXNO+GjzYiZimo6Cq/bDxoDgCRVa33/Z3bcRHjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T12:33:53Z"
    mac: ENC[AES256_GCM,data:XVaHhptYqSIpnOePwVCZJyYZtA1geDY+7qq7hGnpfTvMJHVk6JWPlvTVo5+LguMbTqFhnKVCSgEc1HdZBVQjqFHdz4hT8GIdxHpVdtD+67Ics577WTqftyj8w666yD4AvR3sUtg+2AuILwddDagcriHQJaOIZGHz193eHtJdB78=,iv:abGCQ3Zw6jOKywD0Ukt5ktx/8BMFofVDe7iRwsKCurc=,tag:HIeQT1EnOlLPeAvySkcvug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
