apiVersion: v1
data:
    API_BASEURL: ENC[AES256_GCM,data:ZG1RGFGCVo2HhVd9HQFk8wxkRFtpg/75UbFhz5D9CiofCFIWWlHP3wttqUfOB4RSBfyM2PrwPNQ0yK3zu92aFVuk4s0=,iv:dDWDBGGGUCkkgpt8nc7rDNlax9gfn9vTCVb+sh7vSqI=,tag:naZpi5HLJXSNbq7pn/Ybfg==,type:str]
    API_X_API_KEY: ENC[AES256_GCM,data:H2oiK3rjN86oOegZel1zJyt5S0E1PCwLzLsCVaAx7zR2+GqEpD9ZMtJLfnMboxKj,iv:ax41Dh94Yn3cZyXoM76QaVAIhXWtbVCG+3ZCADt0gU8=,tag:WQf7GUVzXHtHRjKR2QekuA==,type:str]
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:Aj/Nqvl/0403vOMLT9u3GTVIckfA8+WA,iv:XT5eHa65l3bbLtVEJ2XK0sdPAPnCvIpn+Hs6n7HRtjQ=,tag:jfZuJoigOOoajPwOyO+lvg==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:VqhwDq8T6bETc2XTINBoi+UGsTsF2O42Esz4vR9rlwA0CWxJ8sWwJqDKhTc=,iv:uio6A4xPuD9JLZGYomyXq1TwOTSUA71f44r4UpzEAtQ=,tag:N2xEztN70vvow654oP7k+Q==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:hvLfiNDSpodU5M8eeCjv/UACi2Syu8VRKYDKzmbWlTSYWbGf/Efl19uwqYcYzbuzUVqe6/id1Tg=,iv:5ym/kOlf7QLqfSFAy91UZQ3pUcUcZr/6ifPSdK1RQm0=,tag:pYSDVZUVrxmptsRQ+xUImA==,type:str]
    GITLAB_TOKEN: ENC[AES256_GCM,data:ttg4H1naO0ea9X5YGNUaal/eYmFQ2rYpAaz2VLD6bC3E8oEU,iv:AykK1gF4Xu09J82JFHT5ZHaPmiUlXAw5wkB8ULH4vPk=,tag:oiepx63HDRB7WWMsvhMrYg==,type:str]
    KEYCLOAK_BASE_URL: ENC[AES256_GCM,data:BxAb7+ZMwqtSUmJeJjFdcqMWx6/+YRFlAlsfJsKUHQxQy7IpJXxFG4GsxlLJmp01,iv:AdLhbEvDiNturiVOUMDnvdldvTUllfCByqRsWz++lYU=,tag:xH9607SMJzacmXoWbyg9yQ==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:72WwUQ==,iv:MsbgulBfy2HKiOjbAHN0XI71T/f9BBnNg4ko1G6JF3A=,tag:Yhol+F0X80EOjWUgOr3Ggw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: don-crawler-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g59lru89pjncetzrnlr23cc4vq6rct5npsc9xcf89v26slm6g5msh579ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NjJ0NW8zRWRKN3cwRHdU
            VFVvNjJQTnpRbzZmalBzb0hYTjlTcU9xS1drCmU3Y2hJbStteERudjRvUVliVXQx
            eHlJcmN5RkN2U2xuNTI5OEFLUVYvL1EKLS0tIDAxWU40bSsyQ3hvck5FbUdtVVhj
            NHBRaFVOaWZPVW1lQ29EU2JBbFg2cVUKsu8E1n8FdRNZa7BuojuakKI9T2u8GmYD
            aF8Rfzx50QEW/awefkPB8pDsPiBH5i8j7glIWByLufMWd92dZ3lkQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:35:58Z"
    mac: ENC[AES256_GCM,data:2aqycaiPG1KXdOxCocb9cpuR0l0HiZm/cWAHcuXhBKQw65nmfB64pIaz9U8flK0pZZtfFn2PkK7wEWg9XJYtZS9yVOWrGl31IW//ppbM0uck/X13UL0VaAksuoVeq0NUQKImWt9w23bAhGVgnbmXM2FV4J89uK+DJGPpRE9Z34I=,iv:ptQo1eX2ZxFF3oolTStsJn5dpeZ7faS/z1Hc5ZotNiU=,tag:2P/RoNxYzaHrh51CkWHYBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
