apiVersion: v1
data:
    API_BASEURL: ENC[AES256_GCM,data:0RuCUznLMYzbFUbJiMQCa7JAHghsMy3I0W47VliPZwb8QebkARV/fXAXWOAKQhhBH680i5FVvEgDdJa39RlJg+DHGME=,iv:Qvv+aaYbhqxQVLlnFVyqezLGbjNSpC7oJJ0nimpOR5I=,tag:YPO0i3Vmc+VcJJy2omnW/A==,type:str]
    API_X_API_KEY: ENC[AES256_GCM,data:fOiMOEWfC8afj2botpjv/1pgieP4JkWvDq1JSet1ZJi/YtmGTsFSGwFm81buVIND,iv:TDHX6Mt6Y/VolOrpaYtVJ7nZaLb43kqeIL60h0EV+EA=,tag:CYHWaD33Eeuiz24f7tb0ug==,type:str]
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:RUOKyCUkzFq7rWlN9IbMQmtERut0YC8Y,iv:z7/Eo4hHWLokncZaBBPmbHjd8LKPFuNz+1+pxVJW7O4=,tag:OAEWyuOVeSD4CMziGq5efg==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:FdFVHDidZQ8CWYj7oh4JojIUjs4yDZACEepTmb5j+YeB6gUbLlsIa1IQjLs=,iv:a36Zt8anYvbP9ftaObRJYiGpQhmea9fbGZ/h70mVW+Y=,tag:/Ys1/bNyY+I2o7rHtlBFUg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:9vfeeNeq0o96Jif3cb3zOz8WT/dnChpB1xUkrNUXDP8Apd5S4hfn7K574fkKfalQIaufixKo0yU=,iv:fZVG5Scjg3IAAQ8nHzOajP0/g5wXzXTb5MGr1M9ogzY=,tag:fdbG+LJiLa+4Uf7VO3GA6A==,type:str]
    GITLAB_TOKEN: ENC[AES256_GCM,data:0kGcQquTcdg/1XReNZelqbXeHxi3q6iYYr77rA==,iv:0Tc+oACNkFPZS5NG0oKw8eTkp5gCSPT2yNWhrvh16fc=,tag:g1VRQWbu3K8B/M7UydpGEQ==,type:str]
    KEYCLOAK_BASE_URL: ENC[AES256_GCM,data:Zuwj129FtEO+OWKl2wV+GpanjuxcDcQ8Sz1FybAbeBcfVtdTeHvHNRh4I5WXAbAq,iv:3dhAWVDqADwAWarWrrYFiSb8KlY6K7ZbBE1T/gN/SCE=,tag:KzxSSawX3msrF1FEuZeBJA==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:Rgytxw==,iv:Z9cgnPdhLd4oPaMUdYLmaBqSnagSIn9JKoiYFizeP7w=,tag:VC0yAAgsSSfjtIvtFmXdVA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: don-crawler-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g59lru89pjncetzrnlr23cc4vq6rct5npsc9xcf89v26slm6g5msh579ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMWZubGZBeVlkT090c2ZW
            WFBVeU1QTlZmdEhaSEsvYmlVVk5MTzliR2cwCnIzOUZHYWdhV2l1UUFUMXRkVmU3
            OGdiREpjaUlMbnVKTFgrMXRQWkg5UjgKLS0tIHRKTk1CMm5CYUQvck5Yek41UXV6
            SUx2L0U0aDcvYVdvU2lWWVdLaVhUMDQKmqvCN4cOY4PLwPwHhVLaIllhwy/Q7IcZ
            i8ua95P7PYyvpzrVGt6JMOLbbA6YLRkk1uWdm5OtLXvfs54UfzGeGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T09:03:00Z"
    mac: ENC[AES256_GCM,data:0VigYBQJyKHu3hm0AlE2UY7sv5UsZv9IMIQKltWngK/552nlr7lvI37GJwLI43SUabsLvf0MfPEZJoFaVBaNORZJ0umYVUATecGdvId0kDZ3P280M2UeKTFKGDkyGQYo4rPlMQ9MSRefyfUN+P9N6Swdb4UBAO59ugW/HyJMMgI=,iv:fPqIXXgwKcsFy4x9ORK5X2bWV9esyyeXINHNiFluNgg=,tag:hHpMkOTSMmJG4M+4ZugqRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
