apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - oss-db.yaml

namespace: tn-don-oss
namePrefix: don-oss-

commonLabels:
  app: oss

images:
  - name: don-oss-register
    newName: ghcr.io/developer-overheid-nl/don-oss-register
    newTag: 5ddecde38cc42312b2b79ee4857f8e33b35f20f4

patches: []