apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - oss-db.yaml
  - register-site-secret.yaml
  - don-crawler-secret.yaml

namespace: tn-don-oss
namePrefix: don-oss-

labels:
  - pairs:
      app.kubernetes.io/part-of: oss
    includeSelectors: false
    includeTemplates: true

images:
  - name: don-oss-register
    newName: ghcr.io/developer-overheid-nl/don-oss-register
    newTag: eafcb0d7d5d92d1994bc9f6a28bc5d9b60ac6a69
  - name: don-register-oss-site
    newName: ghcr.io/developer-overheid-nl/don-register-oss-site
    newTag: 613088aca7d6f5dfa91ed2d48f25c0d9f35d1955
  - name: don-crawler
    newName: ghcr.io/developer-overheid-nl/don-crawler
    newTag: 36ce1f3a2adeb6ccd163152cedaf8c6e4577ee64

patches:
  - target:
        kind: Ingress
        name: oss-register-site-ing
    patch: |    
      - op: replace
        path: /spec/rules/0/host
        value: oss.developer.overheid.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value: oss.developer.overheid.nl
