apiVersion: v1
data:
    DB_DBNAME: ENC[AES256_GCM,data:E/rxNQ==,iv:UqZOi1lEdNDrd+dgNEIxMkz7Ytlou+94ZKQ0hBkM+XY=,tag:eUtKboL3PDwibPVB6MzjZQ==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:7y9WIas+w5Xga7kJzMxeEfEVKGaGBgbM0Lh0ETqthKnNPISY+YI+jbE+pxvBJuEAJXjFb/1mpoMVv3cGt2UUXDcYfGmN6Axx16XIWt+5ORM=,iv:R2rvYx/Jcsqw2Deb5r0dTW0oY/nLtj8GYXn7v+m4pLw=,tag:Zrt1lymuOxbqnahyIqhw1Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:qH3R+w/jf0NnFBRl/K7dG4wQMAOLHI9D,iv:oq6JSC2gT8aiII59VfMcfCHEuf8WrOYpbUkKCC69NTo=,tag:w+SCVoLiDOJtSVyKaDcHNQ==,type:str]
    DB_SCHEMA: ENC[AES256_GCM,data:AyYPAEG8wilGQQlg,iv:JEkqUlU2/at+uPpcUmyw7T14ombqAxxkj0LelKugWpo=,tag:eck7qbiZw2GtdKdVqoMh3w==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:eIM/FZMxdmDG5dYc,iv:1qEOmf6GoubLq1gt4V1Mvre2cR2sIDhzB224tGA6qyg=,tag:X87sYipZ942s12fYe+MQdA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: oss-db
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g59lru89pjncetzrnlr23cc4vq6rct5npsc9xcf89v26slm6g5msh579ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdFJBa0VlSzJ5WGtYSSta
            MHl3TFFnVTJKQ21FcjBhVDgrb3BEdmtqWkFZClZndks5VkJkaDlFY2RPQWFRd3JV
            OWExSkV6UkoraUZkbzlyTHMxb3grZGcKLS0tIHdxRVlpdlN0M0ltN0FpeWZzeUFx
            QzgrbmZNT0pYcGg1WEZPdjBuMkR2T28KNYva/9uc770ZqbWwC8mbFI/OO1lW8WVC
            BY8oC7hIc0UEElbWPrPFmiY0nv7sEfLWvVFfTjwxLntyc5tAF15D8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T11:05:09Z"
    mac: ENC[AES256_GCM,data:9AvwSEW6xjupU7Qoe1ccw1vFbJv5BAilHUK906n1NbfdGGuRREVg1DDUZQFM8vVUj6hjuW6aGpHVnMjH1qM3T8gW1fAw1BFsAS1jw+K12ATdbQ4Iy+UkRdlImHWW89p7QFl0BxJcki4wBA/ePpQyp5u9Uz4p/cAm3DCYBaxy+AQ=,iv:7JduT3YDgJgXiLWieFa1hpLceGyD1xmyF4edJj7eGG4=,tag:D0gomgtezNLJxdCmbvqdZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
