apiVersion: v1
data:
    ENABLE_TYPESENSE: ENC[AES256_GCM,data:Zi28hwuLn+Y=,iv:tNXcnHKi63U9fANovjGKxupJl/AoRCk6dUW6SN1faJE=,tag:6Tz9RcyinG9UyY2pEbqHKA==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:aigq/GlCAoGZ2Em1v44mV38hvvINwIGN6aacR3UN/hajWYvav8igh0RwrDs=,iv:5ux9GhIElxWMHOCFIQjbYp5IsHHooxYHbewYuzfvh90=,tag:UPcmplOzL1s1vF50RLvZag==,type:str]
    TYPESENSE_COLLECTION: ENC[AES256_GCM,data:yAtD/KDhzUpZGypZ6rQ8sw==,iv:sN4O3mLa0WmxJ9wDpkYXAA1mQv7reCih003GP9UA2qI=,tag:dQ1g2ww6p5qK1wYJLtIKsQ==,type:str]
    TYPESENSE_ENDPOINT: ENC[AES256_GCM,data:Xpo1/fFJ0XVS3QG2E77JZZNc/lJcV8GGf1h5iEoKOFWyG+butpir/oeNDc/irbQA,iv:GPkGd0QAZsCkQxXPH2u79zuXBvYNnkvmuAT7vc/QvlM=,tag:SLxY0aNYIGRhXC8uMEXxJQ==,type:str]
kind: Secret
metadata:
    name: oss-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g59lru89pjncetzrnlr23cc4vq6rct5npsc9xcf89v26slm6g5msh579ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSFExM1NPWVNpQlFnU3U4
            Tkh0K2loSlQvUXFBeWdYZ1ZNdmIzWlpEQTBrCk5BM2UvNzhGWHVzZEx5dlVGTEdO
            eEJLR2RzdHlhR0RGMndlK1hVbnJSaUEKLS0tIEhBYVl5aFJQUXhWeVZUOThGUkE1
            emJobEtQV2NCMytCTG5jVjFidHZYa1kKxFZAmo/qZHLVQV3f54D9oQ+Xw/zDhOXd
            FTw0uToMvTHFb0kzdy+7QeW++gDoJnSM3ZgSFyl8UJVgP5l6t50NDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T12:14:34Z"
    mac: ENC[AES256_GCM,data:fFQvfaSmcwHokPd7DEb5MYBUB78nWMqPut1YXlghDK4SqveGAjimvcF1A9ZEYnGGWHez479XQ299XDPKGFuY/bPtFcmFsn33Fam0ADZDOwI8TQqG+cAolg9K1voF5JAxbzxudW2EZ5GDKM+0+7VVw6eUDWKftKLUDz1btDy+gSY=,iv:73Cz/0nKdVzIZnLD+zp0fChwtt1R9TNCNo3pHcc2fYo=,tag:2E59m8sbrCTPQA6Sd8KLSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
