apiVersion: v1
data:
    PIWIK_PRO_ACCOUNT_ADDRESS: ENC[AES256_GCM,data:bp9JAdLPMkNDubOzZqMjMoVeaC9PbsICqPD1cdTYOsdpKUBnil7s9962CwFDotOy,iv:6fxWsCYgjjiBdfy5Vzl8fthnDgpBr9zDXDbt9qNnx7U=,tag:PIedAbovTYUMiSVg758Sqg==,type:str]
    PIWIK_PRO_SITE_ID: ENC[AES256_GCM,data:rYXqlWxns5j4U+g5BStRBGO4IdI4ZO0WSUVw6Rxa9djepJjkpHVW84DRV09+KVis,iv:3wNBPLdg2DA9fIG3ceJ1VvYSHGK60zFLOqmxRnEYsLQ=,tag:RxAG92ySZHPmRu9XQ9Lu3A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: piwik-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g59lru89pjncetzrnlr23cc4vq6rct5npsc9xcf89v26slm6g5msh579ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNTlMRUd0UWxBWFQ3L0ta
            MUovd24rNCtTOXdKaWRPSC9TVWdXaHcrNmtZCm1CVmx4M01tWXFaUExDUjJoOVp5
            a0NyZWJYZitaTmlBdllPYWUzTlkzckkKLS0tIGVQWDF4L3BPUzZPM01LMHJnUGR1
            TnhyOFVIblVITGRpTWlxM1dkQjVvOUkKGtLub4qxu8dd7ulQ1mRzf9NyYRiUCXWv
            yNfdDIbum9+AyeHii5MvMrESvYJ3coeykQpkrWqzdFlBmt2/nqDZAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T18:58:43Z"
    mac: ENC[AES256_GCM,data:LTNWXVUyPy98HSPdLMWpme59LWkI7vppzBEH03tTaX40V2Qs+3VoAryhnfmNARhYg/d1bBk02fT/dlOGngd/GUAjsGe3Vz8nm6ElR9UNVFzQvulVuWroSliDJeT+6vauKXSYthgfXOo5lTDuuuzs1zeRihJR+6upBflbJyxHaPk=,iv:NdCEgaT7RSwCSydJkHze4W1L7z3Gx1O4xbFFZYVzIFA=,tag:NDe18bwCKSryQpmXU98yRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
