apiVersion: v1
data:
    API_ENDPOINT: ENC[AES256_GCM,data:uTlgjdo/nhxGJ029F7p21g==,iv:HfozqFiJmUwo2XIp44oHBG8DmSdWrk/fPubnBEhwPLQ=,tag:ZuT+JEd7YqPPFoIo1D2TeA==,type:str]
    API_URL: ENC[AES256_GCM,data:0KvQkAAqOEgQ9jtyHnqYUPl9epga2c6N6Lwla0iPeMG6/J0eqI317OvqyB4=,iv:CncU4+QhmigosYHmJUumMdFSBhBB6ydWNW+mmzqTwE0=,tag:Rz9rwu8bajm/fPYqe1ROnw==,type:str]
    API_X_API_KEY: ENC[AES256_GCM,data:F5B3UKvcmJu39XPHbNZXDpjCgKWWVO4lQM4n8AnAOloRNArZW3g/5Q8bbe+y05Tz,iv:GIJVryKH/4HQ+F4ZcVvIGFRN0OqX27vN81C1ZXuaby0=,tag:CUBeokUYavuwUOXqhLe2Yw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: register-site-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g59lru89pjncetzrnlr23cc4vq6rct5npsc9xcf89v26slm6g5msh579ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMURXYlM2RURxS2h3UjQ5
            d1lqYmZUZ2VQZWlBRkR2djBTRDdUbkhGZmx3Ckk1UTJCR2RJeFhWK29PbHBubUZl
            bm40cEluV3E3K1NYV1JCRjVVblcrRWMKLS0tIGdGeW5Tbk4zQWJzdm10UU96b01P
            d0RvekdVZmpsYXBhS29QWmJCRUVuWWcKv9cqbQuGMEdLl9C8CX9MmNZUOIkry+1Y
            U/PGpqMee0DaYJ0f2j5M+YGAOUxP9FqKYxUmVKlTJpnwrfcP5cxGLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:41:09Z"
    mac: ENC[AES256_GCM,data:E/Jfi9TXYALQw3oVo1g+kTMwigxalPiV7nF2ZJuVf8AhWyjKFcGL9tPjqx8dLQ78Z6YAOvMeFNzN470WFFweZZh8UVZCmq8ROTzYwBk5mxA7FwbtAhsVbnv9XsOmMc7/JnKQRK5tsBMncjgGi42tkzCuYT9AKsyb3ofxfiNKj5I=,iv:UvEvI4MGqM854Yd65vgnPIwfUq13Y+PFg9BKRjJmhD4=,tag:E5JeQLZIpgxDoXQQEAhBEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
