apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: typesense
          image: typesense
          env:
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key
                  key: value
            - name: TYPESENSE_DATA_DIR
              value: "/data"
            - name: TYPESENSE_ENABLE_CORS
              value: "true"
          ports:
            - name: http
              containerPort: 8108
          resources:
            requests:
              memory: 512Mi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 2
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc
