apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - api-key.yaml
  - scraper-configmap.yaml

namespace: tn-don-search
namePrefix: don-search-

commonLabels:
  app: search

images:
  - name: typesense
    newName: typesense/typesense
    newTag: "28.0"
  - name: docsearch-scraper
    newName: typesense/docsearch-scraper
    newTag: "0.11.0"

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: search.developer.overheid.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value: search.developer.overheid.nl
  - target:
      kind: Deployment
      name: dpl
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TYPESENSE_CORS_DOMAINS
          value: "https://developer.overheid.nl,https://don.apps.digilab.network"
  - target:
      kind: CronJob
      name: scraper
    patch: |
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/-
        value:
          name: TYPESENSE_HOST
          value: "search.developer.overheid.nl"
