apiVersion: v1
kind: Secret
metadata:
  name: api-register-secret
type: Opaque
stringData:
  API_ENDPOINT: "http://don-api-apisix-gateway.tn-don-api.svc.cluster.local"
  TOOLS_API_ENDPOINT: "http://don-api-tools-svc.tn-don-api.svc.cluster.local:1338"
  TYPESENSE_API_KEY: "changeme-typesense-api-key"
  TYPESENSE_COLLECTION: "api_register"
  TYPESENSE_ENDPOINT: "http://don-search-svc.tn-don-search.svc.cluster.local:8108"
  X_API_KEY: "changeme-api-key"
