apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - apisix-http-route.yaml
  - register-site-http-route.yaml
  - don-schema-register-http-route.yaml
  - apisix-secret.yaml
  - tools-secret.yaml
  - api-register-secret.yaml
  - api-register-db.yaml
  - register-site-secret.yaml
  - piwik-secret.yaml
  - opa-auth-config.yaml

namespace: tn-don-api
namePrefix: don-api-

patches:
  - target:
      kind: HelmRelease
      name: apisix
    patch: |
      - op: replace
        path: /spec/values/ingress/annotations
        value: {}
      - op: replace
        path: /spec/values/ingress/hosts/0/host
        value: api.k8s.orb.local
      - op: remove
        path: /spec/values/ingress/tls
      - op: replace
        path: /spec/values/apisix/admin/ingress/annotations
        value: {}
      - op: replace
        path: /spec/values/apisix/admin/ingress/hosts/0/host
        value: api-admin.k8s.orb.local
      - op: remove
        path: /spec/values/apisix/admin/ingress/tls
  - target:
      kind: HTTPRoute
      name: apisix-http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: api.k8s.orb.local
  - target:
      kind: HTTPRoute
      name: apisix-admin-http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: api-admin.k8s.orb.local
  - target:
      kind: Ingress
      name: register-site-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: api-register.k8s.orb.local
      - op: remove
        path: /spec/tls
      - op: remove
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
  - target:
      kind: Ingress
      name: don-schema-register-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: schemas.k8s.orb.local
      - op: remove
        path: /spec/tls
      - op: remove
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
  - target:
      kind: HTTPRoute
      name: register-site-http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: api-register.k8s.orb.local
  - target:
      kind: HTTPRoute
      name: don-schema-register-http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: schemas.k8s.orb.local
