apiVersion: v1
kind: Secret
metadata:
  name: register-site-secret
type: Opaque
stringData:
  API_URL: "http://don-api-apisix-gateway.tn-don-api.svc.cluster.local"
  TOOLS_ENDPOINT: "tools"
  ALTCHA_HMAC_KEY: "changeme-altcha-hmac-key"
  API_X_API_KEY: "changeme-api-key"
