apiVersion: v1
kind: Secret
metadata:
  name: tools-secret
type: Opaque
stringData:
  PDOK_REGISTER_ENDPOINT: "http://don-api-api-register-svc.tn-don-api.svc.cluster.local:1337"
  KEYCLOAK_BASE_URL: "http://don-auth-keycloak.tn-don-auth.svc.cluster.local"
  KEYCLOAK_REALM: "don"
  AUTH_CLIENT_ID: "changeme-client-id"
  AUTH_CLIENT_SECRET: "changeme-client-secret"
