apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: register-site-ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto $scheme;    
spec:
  ingressClassName: nginx
  rules:
    - host: set-in-overlay
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: register-site-svc
                port:
                  number: 4321
  tls:
    - hosts:
        - set-in-overlay
      secretName: api-register-tls
