apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:9HJiYReQQZzATuQUjMgC6unSCPEoEWkq1imB6g==,iv:NQtY9IhF1TU3Y2RsAL1NFKhWee5/T5XVaQLflqT5Ipw=,tag:Q1e9n/NlZhGncn9NYAD2aQ==,type:str]
    admin-user: ENC[AES256_GCM,data:EJKRLA==,iv:UNaWn/Hvqv5wxcQSAfHtBSDOuZy0wefkMrfIAcgXtDE=,tag:q50PyHdkDmtYH5XqOCLDQQ==,type:str]
    db-host: ENC[AES256_GCM,data:tJP9jGPG3j2/NuK94Lt8ykOZq3dK1N0ejKxs3cBAtRgjq5OtZbAiYIBjx4e22mTd4QfXHkQKSTWOEZE1E6KT3hf8UpuniYM6mC3byGyZ1sY=,iv:9ZKIEDOnfTxQliNjWqssM2WVIMbNjHv66//bnSXubDI=,tag:lMwS4dkVtSMIJb/vE/xiKw==,type:str]
    db-name: ENC[AES256_GCM,data:7k7+sQ==,iv:r6LQA8hceRQyJBCfBN7wLRWo/jFpbGdz1wkBmT5TgtY=,tag:2QAfhNekFkZ8MIKWNoxtaQ==,type:str]
    db-password: ENC[AES256_GCM,data:+/KjR19bTuG2eWwrnJsW6pIEB3qGBNGE2CMJ/+Lb44Ar7ITb,iv:AMSj0Jg3Tv7s0/00lxvw4VbgX+8zujhYjeM/SAIngvc=,tag:hhYhNWKSLV8emwwgs7uoQQ==,type:str]
    db-user: ENC[AES256_GCM,data:iEcibw==,iv:WI9qTbwp+fi871kxeeQiADl5kNMlq5SKrQtbOavu8J8=,tag:sv+Nowa7M/9HCzBnF5jorw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-login-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13lfhkxpletvsxwz84p8nllgahsp8l350a2n7kdthh3tle78xgerqwhqk27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSWI0VGV3c2E0N21NYSt2
            T1Bhb2N6K0pod2tCbHk2TndnMFE4bWQrUUJrCkxSL3crdGROSmlFSE9CS25oaEda
            NmFLWjVZN1ZlcE42RWhzMXIzTnVmTlEKLS0tIEJ3RzdoMit1ZWFWRXJkeWRuUXFB
            N1dmSVN3NXUxTTNlZDVvL0NNb2IxdWcKdu8SUTv+AUb8By1hxUA7vlKmiZV3DMGr
            MRnintSDl9rhkSRvrZvAR48udmnbwuec056oBkR0nGTmb+R9o6swEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-29T11:34:01Z"
    mac: ENC[AES256_GCM,data:ROET5cxbDD/bF4kaHFC6T8ku3LQHXj3AL0fuFGs3uOfgdUrZQpDafcoKxOLPGjG7p8N6SHbmZk+qFYJryXdArE4uHOum3EQqyXTpFpOMooShdsWSbRVv0gz8s/TCzTFHABB5e/mjvB9bPDLQLBJ8WJ4aP5TrtbJZabqL/csW/FU=,iv:HQ/65TY9c8KdkIPt1FxhVyc3GJ3J+wqxE+DcaPz723M=,tag:JY5VnimAJ/4DP9P4eXyPgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
