apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:XAgvezF2cwO6klQtyV/mhWat9Z7nhqIoY4ZB7EbYg8NYDJ6Y1UC1FzaG9jUc3GN0ogg9dA==,iv:pZxfJTQac6t2EIeVygF0enxzKAlNTE1HzGC+Z+WZ83g=,tag:a0pgEkfz0Wt3svfKVZ7yqQ==,type:str]
    admin-user: ENC[AES256_GCM,data:KHlVgw==,iv:fTM7UzA3dRm29j6V6S1+IggZmjjEUViNbQ8++aZ+1dI=,tag:ExfFhEf67SriW8m9gW63sA==,type:str]
    db-host: ENC[AES256_GCM,data:PQj0TJwz6DEO9tzqhOa+EKBDUsKrm4eQnkCGxJw1Lu+J4kV0lhXHveoOlgI=,iv:3p2JhFjx4N48k9/5hXraPHk8D/m9YynlKSrLhGF6Oa8=,tag:UxkEzmrylinOEZWxC4dApA==,type:str]
    db-name: ENC[AES256_GCM,data:qd4i+g==,iv:LbxhU4h3M0sAno6TkGtctS370BAUiQs3BMOt4MSW1o8=,tag:t7Lw3jBRQ/e4IWDpcYzTsw==,type:str]
    db-password: ENC[AES256_GCM,data:1m7miOZFcgYAJ8ZC31Bw5SPQvVGYWyxXcBh5SuU/8/cim+BN,iv:ItW+qPfDk3UQgXMqCRF0HclglnvZtbF/j/XVTK3/5k4=,tag:QfmUoBSiwfoh/B7DLZ7oKg==,type:str]
    db-user: ENC[AES256_GCM,data:Ne75UQ==,iv:ZNcfShklDiB/a33tD6pbdgabz7uhF59W25kW6NbNnD4=,tag:1uE5v+L8iUBm54/O4H+TlA==,type:str]
kind: Secret
metadata:
    name: keycloak-login-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13lfhkxpletvsxwz84p8nllgahsp8l350a2n7kdthh3tle78xgerqwhqk27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VVNRb3VFdFdVN243MXJE
            QUhSWGo4QzJZQmY0Z3JKZXVJS1hmUGtwMnhrCnFMMndwRVg4RkVyMDAwNHZhc2VX
            N21KTjFvUHRiWkRsTXNIelJGOCswcG8KLS0tIDB3WEduL2k4NVBQU0d4YVlsTktW
            V1VIN2hiT3Q0WnNyQmI1Y2psN2RSUVEKgvpg9Fg7X/X2q46/DS0HGXoaMc1vPRIg
            F4t2q2HvxsH0rAagRQ0aMgd38q4nKQLDQOZSuOkzzrngLb03e/6eBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:26:04Z"
    mac: ENC[AES256_GCM,data:5bzM8zWDt9PdpBXtfxB1iPPEaRXo94cFbMahEb602tiPMO98I9E3kiZ9Lp/aLDVg4TDlGJDR+nV6xw1vO29mpaO/0bCgHyeml1T7ly0V+nNXV2n+Lag4wvAHeD6JCWayZHY02QX41WMAW62UuL9C3t5wenumuNl7Dd2U54aw1C8=,iv:qmmhMwGsoRLAnzX2N4bsq3oC79+ORh0BiujJxrozUcE=,tag:vxwY4rwxYQASAtzGXLKLYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
