apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:IQwBHcd7W6+pre/GJxettPgWKPYDsnlV3gN5og==,iv:mE5dJthV2M9pWvj3Iql5LVad2WG/OsKXgfkMjZqodP0=,tag:u0nycgpIhRO7NIgClM6grw==,type:str]
    admin-user: ENC[AES256_GCM,data:8tooTw==,iv:/OMzDRAI6VqEFD22Oxihb46fKTlC4g2A9J9MS/a3EBY=,tag:Q5Eq1FaPpeUZeSIeODJKVQ==,type:str]
    db-host: ENC[AES256_GCM,data:hnrhT5gqiX3RJzHWg1VUdHQ1o6MzgUKFOWU3Q9PDh1Qrn2mZd1FrZMlpECcRie/c2KU/DLXDmmaW2JdjJXI10dH9xSeKH4CD,iv:i2lT0JeOJ7fBbH22BM4x4pdAF36wqXPofwf4IzLqhDs=,tag:n16sJRg1AfLjt7kpZM+jMA==,type:str]
    db-name: ENC[AES256_GCM,data:RbGq9tCingsY73BN,iv:tY7pVtm1cEgrkErgZWjUecPxOPDdq3H7UEjh5dd78ek=,tag:fEC5xoWyCbnXslg1yRZVeg==,type:str]
    db-password: ENC[AES256_GCM,data:wiurlbMRlEUOGKUL/8IF5QZjn+fmkz39asE1XL7p8oAlYC+z,iv:o78qDcfkP3JPCUN2gs6uwxZm3L/slQ+zFAxLjdrK+VM=,tag:uv84AFumeUXXJvrwy0Gxsg==,type:str]
    db-user: ENC[AES256_GCM,data:A6OM8PJkuAUU9jtF,iv:39cfsj0mw5wCnbF4ty24zZBS19YXvFRjENxyrKcN/Uo=,tag:YlHMPoulojmtBja6/3q/7A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13lfhkxpletvsxwz84p8nllgahsp8l350a2n7kdthh3tle78xgerqwhqk27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaay8zWjhMU3VTbm9kWVdj
            STlzclBKanQ3L2lpdzNnb3hnNUZsOWY5OTFRCmZwNFhzMFRkS2l1Uk44NlBadmRx
            dEh2T1RZNDlRRUYzMitIdXBLVlBtYkEKLS0tIFR2OWluWjA3V0FTMlAzMjcvTmxT
            ajFOVkJoeElMUnVrOWxLSDhad3FJSFEKF0zADbkdcodQR1A/mPBOwdL9rUbLXYO/
            tlPqLzyJ5Ee8Po45eZGpBMt57rT2SCf6DAbiUPKykUc4BPCAHWKYYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T20:14:55Z"
    mac: ENC[AES256_GCM,data:5vxWcJCkDaix8EsNPoJYz4kbGA3X4Xq6f7G34z7oBHgD6UNvOjaFZEfMaVfoYONN0tONlRvhnrycxtFi41uMSqxEk8pSWrUx87Of0puISogYlRnVnSewy05VJqoRXBsf5JnaXO4NgHwG+TELDK1ceCfduOZBBQQGToubZDN1mrg=,iv:BA0iMlfFmMHslVhP9CHNlKSLqWiqvO2GdRIpioUY4VY=,tag:F/7GaktmPhzWFiluDVH+og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
