apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - keycloak-secret.yaml
  - keycloak-realm-config.yaml

namespace: tn-don-auth
namePrefix: don-auth-

commonLabels:
  app: auth