apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-apisix
spec:
  interval: 5m
  url: https://charts.apiseven.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apisix
spec:
  interval: 5m
  chart:
    spec:
      chart: apisix
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: don-api-repo-apisix
  values:
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: set-in-overlay
          paths:
            - /
      tls:
        - hosts:
            - set-in-overlays
          secretName: api-tls

    apisix:
      extra_lua_path: "/opt/?.lua"
      plugins:
        - keycloak-api-key-auth
      deployment:
        admin:
          allow_admin:
            - 0.0.0.0/0
      admin:
        credentials:
          secretName: don-api-apisix
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: set-in-overlay
              paths:
                - /
          tls:
            - hosts:
                - set-in-overlay
              secretName: api-admin-tls

    podAnnotations: {}
    podLabels: {}
    extraVolumeMounts:
      - name: custom-lua-plugins
        mountPath: /opt/apisix/plugins
        readOnly: true

    extraVolumes:
      - name: custom-lua-plugins
        configMap:
          name: don-api-apisix-custom-plugins