apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-apisix
  namespace: tn-don-api
spec:
  interval: 5m
  url: https://charts.apiseven.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apisix
  namespace: tn-don-api
spec:
  interval: 5m
  chart:
    spec:
      chart: apisix
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: repo-apisix
  values:
    replicaCount: 2

    gateway:
      type: LoadBalancer
      http:
        enabled: true
        servicePort: 9080
      https:
        enabled: true
        servicePort: 9443

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: api.don.apps.digilab.network
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - api.don.apps.digilab.network
          secretName: apisix-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod

    admin:
      allow:
        - 127.0.0.1
      admin_key:
        - name: "admin"
          key: "super-secure-password"
          role: admin

    etcd:
      enabled: true
      replicaCount: 1
      persistence:
        enabled: true
        size: 10Gi
      auth:
        rbac:
          enabled: true
        rootPassword: "etcd-secure-password"
