apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apisix.yaml
  - api-register-dpl.yaml
  - api-register-svc.yaml
  - register-site-dpl.yaml
  - register-site-svc.yaml
  - register-site-ing.yaml