apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repo-apisix
spec:
  interval: 5m
  url: https://charts.apiseven.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apisix
spec:
  interval: 5m
  chart:
    spec:
      chart: apisix
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: don-api-repo-apisix
  values:
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: set-in-overlay
          paths:
            - /
      tls:
        - hosts:
            - set-in-overlays
          secretName: api-tls

    apisix:
      customPlugins:
        enabled: true
        luaPath: "/opt/?.lua"
        plugins:
          - name: "keycloak-api-key-auth"
            attrs: { }
            configMap:
              name: "don-api-apisix-keycloak-plugins"
              mounts:
                - key: "keycloak-api-key-auth.lua"
                  path: "/opt/apisix/plugins/keycloak-api-key-auth.lua"
          - name: "rate-limit-by-keycloak-attribute"
            attrs: { }
            configMap:
              name: "don-api-apisix-ratelimit-plugins"
              mounts:
                - key: "rate-limit-by-keycloak-attribute.lua"
                  path: "/opt/apisix/plugins/rate-limit-by-keycloak-attribute.lua"
      plugins:
        - authz-keycloak
        - limit-count
      admin:
        allow:
          ipList:
            - 0.0.0.0/0
        credentials:
          secretName: don-api-apisix
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: set-in-overlay
              paths:
                - /
          tls:
            - hosts:
                - set-in-overlay
              secretName: api-admin-tls

    podAnnotations: {}
    podLabels: {}