apiVersion: v1
kind: Secret
metadata:
  name: don-crawler-secret
type: Opaque
stringData:
  API_BASEURL: "http://don-oss-oss-register-svc.tn-don-oss.svc.cluster.local"
  API_X_API_KEY: "changeme-api-key"
  AUTH_CLIENT_ID: "changeme-client-id"
  AUTH_CLIENT_SECRET: "changeme-client-secret"
  GIT_OAUTH_CLIENTID: "changeme-git-client-id"
  GIT_OAUTH_INSTALLATION_ID: "changeme-installation-id"
  GIT_OAUTH_SECRET: "changeme-git-secret"
  GITHUB_TOKEN: "changeme-github-token"
