apiVersion: v1
kind: Secret
metadata:
  name: register-site-secret
type: Opaque
stringData:
  API_ENDPOINT: "http://don-oss-oss-register-svc.tn-don-oss.svc.cluster.local"
  API_URL: "http://don-oss-oss-register-svc.tn-don-oss.svc.cluster.local"
  API_X_API_KEY: "changeme-api-key"
