apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools-dpl
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    spec:
      containers:
        - name: don-tools-api
          image: don-tools-api
          ports:
            - name: http
              containerPort: 1338
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 1
          livenessProbe:
            httpGet:
              path: /
              port: 1338
            initialDelaySeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 1338
            initialDelaySeconds: 3
            periodSeconds: 5
          env:
            - name: PDOK_REGISTER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: tools-secret
                  key: PDOK_REGISTER_ENDPOINT
            - name: AUTH_TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: tools-secret
                  key: AUTH_TOKEN_URL
            - name: AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: tools-secret
                  key: AUTH_CLIENT_ID
            - name: AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tools-secret
                  key: AUTH_CLIENT_SECRET
