apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - http-route.yaml

namespace: tn-don-static
namePrefix: don-static-

commonLabels:
  app: static

images:
  - name: static
    newName: ghcr.io/developer-overheid-nl/don-static
    newTag: 8b8602d9fb8959e38a5a29ba1f46a44b65943be8

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/ingressClassName
        value: disabled
  - target:
      kind: HTTPRoute
      name: http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: static.developer.overheid.nl
  - target:
      kind: Deployment
      name: dpl
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
