apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - http-route.yaml

namespace: tn-don-static-prod
namePrefix: don-static-

commonLabels:
  app: static

images:
  - name: static
    newName: ghcr.io/developer-overheid-nl/don-static
    newTag: b9342c5bc0e61f04742df858ae8eb6d990526485

patches:
  - target:
      kind: HTTPRoute
      name: http-route
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: static.developer.overheid.nl
  - target:
      kind: Deployment
      name: dpl
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
