apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: tn-don-static
namePrefix: don-static-

commonLabels:
  app: static

images:
  - name: static
    newName: ghcr.io/developer-overheid-nl/don-static
    newTag: e282c0a1b219a400a1e11d40f6fd10e448056b2e

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: static.developer.overheid.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value: static.developer.overheid.nl
  - target:
      kind: Deployment
      name: dpl
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
