apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-register-dpl
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    spec:
      containers:
        - name: don-api-register
          image: don-api-register
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-db
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-db
                  key: DB_PASSWORD
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: api-db
                  key: DB_HOSTNAME
            - name: DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: api-db
                  key: DB_DBNAME
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: api-db
                  key: DB_SCHEMA
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-register-secret
                  key: X_API_KEY
            - name: TOOLS_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: api-register-secret
                  key: TOOLS_API_ENDPOINT
            - name: API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: api-register-secret
                  key: API_ENDPOINT
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-register-secret
                  key: TYPESENSE_API_KEY
            - name: TYPESENSE_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: api-register-secret
                  key: TYPESENSE_COLLECTION
            - name: TYPESENSE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: api-register-secret
                  key: TYPESENSE_ENDPOINT
          ports:
            - name: http
              containerPort: 1337
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              cpu: "2"
              memory: "2Gi"
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 1337
#            initialDelaySeconds: 3
#            periodSeconds: 30
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 1337
#            initialDelaySeconds: 3
#            periodSeconds: 5
