apiVersion: v1
data:
    DB_DBNAME: ENC[AES256_GCM,data:gXbmGA==,iv:T4Dyo9i9z/ibaOer0Kpljef46vsw1XGodDecAAXHVCU=,tag:0rcpxf9TFXuCYQ6e6Q3yLw==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:dbM0rf/2nyDUSJXTDVO6ytHzSfHCk2fq6TJVgaFPmPEhgd7cgLj3apcP9ak=,iv:b75dzhEsJN8QrE/vaJ3G7nuoooLyk3tcS0linqSUDkk=,tag:ZFem5U8oys+RL7dahvHceg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:sIXcrrh6gtFJnwtU7+n8ileJUeeHb8eUjWMhgaUjXNFHCf6P,iv:do27kz7AUpo/NDEHwic0wMZxp8RFuHi2QE4yGZRG+/E=,tag:Z4J7xD37mja0LwiUt9p0RA==,type:str]
    DB_SCHEMA: ENC[AES256_GCM,data:oOl3eCIjUpACh0Woqf1xv0fIisZxDOWH,iv:Wp6SMOiyZoFOFhhbz3BvxK2S5XJz8TicdAmdeThHBJA=,tag:f3eBvd3cnXcO06FYoEHMHg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:PWLvOA==,iv:YlifGEskK0VITxTBr9j0j4QF1fyxV8Ej2FeoMATSWiE=,tag:UrHudxepeC72/eCiIHyZSw==,type:str]
kind: Secret
metadata:
    name: api-db
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENEZNb2N5TXg1cDF6U3V3
            cm9EUTZwRUxVcjZXOFVBa1FPMUtZY295ZURjClpqVGx6Z2t3OWd1OVpvVXZNK1Y1
            cjdsbHlaODd3a004MzlmZnM4YUpFVDAKLS0tIGc5MDc1S0ZWY1RqekV0ZjVOa0Jo
            MEpNUUlqcVdJYVJWREI4V1NrOVUxbVEKaeZGu/baWTRGQwTVnycCeX2kfEoLdcF7
            9huZR4b9eFd5h5QImhaV5hentYz9rVVL6kCIpZ3tX9PfnlBXrmykSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T09:14:39Z"
    mac: ENC[AES256_GCM,data:YqQqkOlvdoLksntDXnJuiyJuvI1IRBmclr32YVUv9EFeYpSLPNW8ncvSQoPm8/PKgmUeGHc/xaSkZDlFtfqbLtpbWMmBtwKuL0s2pwt/eUg1USQIUmV2gMkbg4U6k7t63WBWbrJe913MJ3GA8LjppBxjPk9mvxIjI2uW7g1IED0=,iv:alZzsI2eA91UpLDrw4DOyIHP5Ep0y927aXcMEQ1mOzE=,tag:R54PnTzU62rYwVf987IJxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
