apiVersion: v1
data:
    TOOLS_API_ENDPOINT: ENC[AES256_GCM,data:nNPgqXQKqz0L8F+piumQ7P4/lQhqx0Lrfp1VylpyPxXlVhE7PD3AWSgU7pnpQsWZZZgVQVyAoWE=,iv:ctsaGpLUE0iZJsrAJ6mn9aoj9hE14tHOS/SFF7Le6vM=,tag:Wb5CYK7BwJEARwhXH8KPsw==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:nYragHbh8PK1B8hRqWuy5WvHdgeK3gxVjtV8rW2Wfs7BpZ8bq9omA+8vlltvjR9u,iv:Ynf3PLs7oXkz8JyPdmEK0JruVTzjIRGPquzi1QAPKJY=,tag:Bgx4Mx9BkJYi1thrplvMhw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-register-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdU5hYU95Wm1mZDVGcldh
            cWdEMTR0K2pkbkNwdE5RdDBjUGFhNUNSTkJNCjNpc3VMcEp2VzdueWhlT1Z6NjJH
            Y3NnUGRscHhiS0srcEJlTkJuQnhUTTAKLS0tIFFNSWtiS3ZJZEdOQUUrMm90N2Jr
            bEd5V2lMcTBJdG93R0E1V25ybVN2dlUKHrt1vBQywCKpo2Jpl8WVsz0TIzNeYXbU
            MND5JgmrHI178SBAwHRrg01akNNDt+ldpe4sMaGaaK6qVV/bhLyV0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T13:36:52Z"
    mac: ENC[AES256_GCM,data:AVInXwIQiyQCEODcOSEznPKEXxNmMOF2ExtuU9B7+ut75nAuwnAgAZFm85sSTwNQYUAuBBC3SR7TeUez/1+Hfzo0kIYomNAoEUjcSTaYYMtMWzOrzsLZ69ExJlU0a255gEPIAvo3klsyBiL3spn8WDLXx1Q/sYMv1TDMm+fd7QY=,iv:00/Z06xmDghv6NdW0EmxrXCHdB8uTAy5G4gOdb/PwR0=,tag:1gqloaZnITmVtJvSdF4ORA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
