apiVersion: v1
data:
    X-API-KEY: ENC[AES256_GCM,data:LOiZ+TYHO3EHuYkqS1/yKkYJP6ak0au7+ViBHXnJWaLApyFbbc4RFv5yx/PCGYP/,iv:kxUzWYj5Izj12IGGEBDz+uyyKXmatCBpDCI/p0RjrPc=,tag:nhtPlxspzB50ozBqhZm+Xg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-register-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM2Y3bWJibjBJM1l5UEI0
            SWFuUTFyQ1ZUYWdzemIweDFMZHJvbEdUdjJnCkxhcXg0RGtueVhsN1JLWDFvbGto
            dkw1VmVEQ1BUVUpiNmFGUlp3SlB6SlEKLS0tIFdwTUlrMTR2blVUVFl2bC9iUER5
            Q2NtTlZBalozNVdJcWV4R1JaZi9reWMK/x0gFv9R7LscDxS58IyCNvnYcaPko+Vn
            3ysgGscaborKiWMYEuIR7uuBrtLmIatCZ/1j7rU2lJ8xjewt+z7dIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T11:27:07Z"
    mac: ENC[AES256_GCM,data:MhYephyucSApn4WMNM3tgl7n5qI9vFJPy+/b4WhNDz1UruwwaRpyuvllpxGnlaBALnz4vsf7LEmCPbp36Jip/rrIkLgfAnYzJf4XRKEa04VP77Ak5xyQMhTLLlNKjo6ekdJRgSEM/cvmFiL9fY0i24fLByJy/bWehSdxYJpihfM=,iv:8n+zZP4wXQdIkDS+Nyi/qcej6z7/7RN+MFcsRM5pWUY=,tag:wT48/oKwod484xvRt+2f9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
