apiVersion: v1
data:
    API_ENDPOINT: ENC[AES256_GCM,data:v0huh+e8n4iVqdc44CAIqkaOKNaACo3j8i+wT2h2KpxyiPZtvSE47Gt3eBShZaLMYWdNtefrjUA=,iv:UMfVBG+WS6+8mHPwmEQQtXCAxNz6IFJfRFRIHAQJo4M=,tag:jsy+k4DfIu6ycCs31hfmOA==,type:str]
    TOOLS_API_ENDPOINT: ENC[AES256_GCM,data:Z2EqqSOCcoyU3arikIKhDTmFldTGeIyXrRRuPwiRqYyKf/Qo760SdifnjzxeNq4Gq5Yg9CyMyn2k5QKO,iv:BYqBTqF2cPcPWIwZLVDra3lTxA7dMp7KsvKWiY82Zjo=,tag:DLpZq3YHItLE2kZREfqnxQ==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:sxBuHTttE/UZxVq79ToU8J/nZhfokb+XflVTpBFYzs0sgCCB,iv:90le3vf4aBNHYRqgjovPKKbY4WzT1uV3LT9/klXtzMk=,tag:8EG+M5sKlEMkryVaX0RXvw==,type:str]
    TYPESENSE_COLLECTION: ENC[AES256_GCM,data:BALUFW6VciyhHYpcPHsndQ==,iv:bewHA181niER7jXUwGv65YOqQmp1qqc1YOFraZ9CiE0=,tag:Mzy4rPAXN5Iv9Dkk4pEDfA==,type:str]
    TYPESENSE_ENDPOINT: ENC[AES256_GCM,data:Kk0HflsCnpnZsrvc1KFQi4HfwNjCMcJPXdXFuHTtE248hAXcYNVjDex6DYyejOkI,iv:TwjcvOWDQ9zrEXPxpB/A7AdSAkPR0oUIAKWfCYZqn5g=,tag:849ZzwB0o+lXYwOymiCNbg==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:btANtP2hBZ2acytq5f5bpOLfsENOs4dDfN/UUUbO9k8Szq25bOFy2NnWXtvH4eoS,iv:rI7It7g1ppma8iJDOi8X12IYgILO2vjXOmnbKlMSCv0=,tag:cpgIk9NoD71PQqQXTGBI2g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-register-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWUlud29xOU50Z3V4N01B
            RUdVL3hqcjYwY08za1BwakRUcmNUNGlyUlE0CjdBbjdOK1F0c0RpbUgyQ2JmV3Vt
            K3FUR2h1MVpZOXJWcnhZK2J1a1ZtNjgKLS0tIHFreXNjZjN3cDR6N1ArLzhXY2R5
            MEhvcjFBbUJOZG5qb2pDZTk0Z1IxTVUKgRz40VGy13DErbjjbxaPnviZ435HwSvc
            PMl0c7XIIMGLd3fObGP0aved0IerkvF+ioBB2Kge2lTTsscFsm9bQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T08:39:00Z"
    mac: ENC[AES256_GCM,data:9CU2/ezvRUiLDTDn+/95DB6gANKp1ospXUV4aqBCAdCQ2Ejh7XD+ePoFv2f2IKHBl21El3WxC8Zbe9LzIXeuRW/jYRpdpgumC4ntEOlmw9596/iRKmOjCAkdPvlbyCyDD8TaM8AOlc8UAd/CMDyjSgymDITY2ThbzypJ20vxArU=,iv:vEkk1L+MOThBTWkA0IhT8pPOUMPxJFsLe9ZrYFPn0xg=,tag:ljF5HFkH3NelaeZXc3fQYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
