apiVersion: v1
data:
    DB_DBNAME: ENC[AES256_GCM,data:1RgQ/Q==,iv:7BfDQ4whnpbbiXmq8H627ycfRj//lU+jO1Hy42NyrVg=,tag:ikZd54jHZEan//HSMxn7tQ==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:3cwfpHYl05RX7s9s2RVxAMav+opXo/VPIUnoQ6nNdcxgM/U00FzqJq7r9JeXQ13V0VkY14JPpMrOOGiGFJRnhF2T2NWlzvDnXo+yFE/PzDE=,iv:89uSs5Kh9JCG3U/ijlLpVl6G5ElUeIgea7ZGbs/qK48=,tag:6y39ELqTCbG1eT4QP/Yeug==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:xrXecBa/K8lZsYjXrHQIwn+wSX1AhxUiL/1zrHoIRNRSmrAF,iv:IsC3ngKvqKmpolJxvx6NFpbjMEnoRULmIw9wUialaio=,tag:Egb4fI4kbGjWQ+i3qrDzig==,type:str]
    DB_SCHEMA: ENC[AES256_GCM,data:iA4eEEyBf+vSkDWhT4Fq0Pww+l3Z9TBY,iv:bg7DgyZPAofS54sQv8g9zXX0ixlX0hpMND336DSS1u0=,tag:wzilQeKGc3BnFK8l+sqTUw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:OwCskQ==,iv:vt6ewqXnNQI9cth6YpvMc9n0nZMpqa8UfIJDY9hMz8w=,tag:jXt/aUUlmpQTSSMKVTL6vw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-db
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbnJqeHpYbmFKcHFYRXRK
            UHB5bHdkalNpN0tVR3FqQVpsSmdVM2duSkNVCkN3aU55MmJyTHlUWnZUc3lKbEJJ
            ZkFpMnFnVmNaV3lGUVlzdjN6V0JydUUKLS0tIHVWVk1WQVQzNEdEMmpJcS8ySkVp
            ZHBIb2c0SmRwT1RQeUtXaURBUGNhaHMKXI0dEUFSznSwvInXXlQiNlGxJY3NEGdd
            LtYXnCYcqznXDsPUNb9yM/QtCtfUCcrkmclDBMVwjv1PWE1Mu3ge5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T12:07:05Z"
    mac: ENC[AES256_GCM,data:/B3QjinPPUAIxZjqDQeZkkE6GPSRNfDUFJpEDIbJH6mPL0iHdcTSrEo4EoV8DUEAGOTaz6dFzRjlSo8Jm6Wy14FG/C4QsNJ98Pj+jX1eHm0h+csQVGZ0e0cFkTnsDvstZRqY+dESvj4RfxpjPLo7dSiItrGBiZySQQ3q0vR2DZc=,iv:Z9O4bzr6j8Shr2zbB2u8gGYm7ZnTXJi5IGT4N+ij7ik=,tag:9f6cydzN8bJbTLBekEYAZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
