apiVersion: v1
data:
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:CM3XuplHAj+T4aXVcrIKVH1Rw5EkgMpy,iv:y9cVqrtifqJv03OUuZ4D4B+a2I/U3q8qVFxDTdTpmOk=,tag:QQ04yurYUQV8j3mNbiIBNQ==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:yqJzrw==,iv:u7q9ED6jAzA4Pd3cxGCmU2C6PM1Sir7OPdO0KXz+Nvg=,tag:ualwzY2AVgGAqtml/eQ4rw==,type:str]
    AUTH_TOKEN_URL: ENC[AES256_GCM,data:ytpczCXMooUEMGNQG1RrQjhDC1TQaqjT05bJaCSfi9qCdxfbOeUX6NE95K83tbalOZp1r1SETu/rPEFEAzdyZ7B9zjlNuTsPI4euyDpCXThGf0y/yuMSBWfCV49gyEhydvrEfQ==,iv:rx3kv4KFd2c2xmSkzQFDC75gx+iR9OFDCWTD9CxLzLo=,tag:cdKZnIgLmQMf6Rw/e/gH9g==,type:str]
    TOOLS_API_ENDPOINT: ENC[AES256_GCM,data:lw3LqPDj3sRuB4EEe4eGRzstxVuUijDvUn/K7t+p0Lh1fbMH2PtYirWfyF0JM5awgepXD/01+8o=,iv:EN0kBjLmDoxeDo7Gf88nsgiTyzvE5dNbcCom5H50WhU=,tag:W17Q7JPQnBobvytZKorIUQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVE1Bc0k2a2UwdWFZc3F1
            dllpQVI5Y3FLajgrTVA3QWNnKzZEdUtaWjNJCmk0WnZ6Tk10NjgrYmh1bkozS09X
            bjJvQ2tkMHdYMGhNMWFQcXVwVk5ub2sKLS0tIE1ZTCs3Y1VBb0dIemE0L25OMElj
            WU9kd0oyY3UyZnNzNnNUU1ZlNmsvUWMKMKYghmAKij/MWVzrVskHe5L0kqRFB+sx
            dMsOlpPCX5zZe9IV/RVaJ5qHhepawi4ZbNgqctWJAXFux+Va6ec3Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T17:36:41Z"
    mac: ENC[AES256_GCM,data:VARgOvTvpg/qOhTco5kDqIeqCKmt041A33U5697gMGt94iJHZZxHy7cLeIfo9acXr/hUr3DUeHkUm4fA4FTDeZaFKYd5xkP439YMqe7T5k6RJI/F08ocqSbRUU7LdSOozQWFDs1eP/APmt1ozdM7GctuiQZan/BxcmsRlmoZyVI=,iv:77mNBzNW2270jXrSfOctnYiF/P4EjN2eyh55kyp+C3c=,tag:64Oj6nLVuS4dE1t1PrYmkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
