apiVersion: v1
data:
    admin: ENC[AES256_GCM,data:h0MVsNrjCqDOlPqmqwAzW8kO69B79XxNNqGPoiRgw/WZpUT63BVMJ5LuhUw=,iv:AkhYdG/XRRq5kafKUGwLTJz0K5fv5RrLjUhozkqtZMo=,tag:Y7bX49qykwFtGT5fl6MFPA==,type:str]
    viewer: ENC[AES256_GCM,data:TJKD3BgKkXlxaw6VFqYYuzpmvUSqyjAAgIOsKL6hWeR4PbUgiRmd0KBHIZY=,iv:vGJWXxi4JFsTpl/Q0S0G1cREmtDsRL597Ym1mHyqAis=,tag:Ql+AhTlyMqyZ6eKxFswWvw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: apisix
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZmFGUCt0Z3pyK3dpNStE
            Z2xYaCs3TThVSldEUEdDMkhsSmZWaGFyWG1rCmlPdW1XdGgwWlJwQm1PbWl6YUhI
            VWVOa0JVWUFGMXR4MXJydWlTT3YveFUKLS0tIGdvVDduYit0SGFUdTJUYWQzYVJs
            VjVGR0FKVHNOS0NKTjJwOVQ2R2ExSjQKYec8McRuisEYkCIG+QnQN1f6DuAB6ZKL
            Zg3kFTAGA9KeUoPdFw5EaDMGEM4IsWNtmKsgGETotXuwhlYlgpaNoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T17:46:27Z"
    mac: ENC[AES256_GCM,data:jIPsQcAbghrPu0HxvOXF57Vtt3LAtjp/HymYyvXCehDj5I4kR/ZpdYEUdIbHzrS+H4K97MHcCkl5GHaXmiKVptDPs+H5TMXuSnr5TyEJVmWd7u1Lanrp0pXTGUXkUvCYHQybrtdmqDQT78k9CD/wPEplLx7ggD50uSFBaNy+1Wc=,iv:5AWZsEfBabqvfaweHEQz7gNqbS0W+uQnjrjJmuGaPAo=,tag:/F2Zm3GJvR9hm3Enrr0ZLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
