apiVersion: v1
data:
    admin: ENC[AES256_GCM,data:OSfOXLtuXJ3QCSXjG0znvgvZ7RLql3o+C2dMMK3GDHrYnAfFEbHG89kPSLs=,iv:9U5CPg7U1OYB/CrTYMXivqk+mabZ06cBuuNORDmQ6Rs=,tag:fXioaOY32ZPsol5lhtgJsg==,type:str]
    viewer: ENC[AES256_GCM,data:DY/LWshUTfWJQrThNLmH/+twVGEd/kKMKnL7MTmDnkQdrh9NC2KwKMCD4Xw=,iv:khp0HgfycdzYHEuq9fDLzZkHdXx2su65jyf/9zCL8pQ=,tag:YVWn3TK+NteNaEjckjbdKg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: apisix
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhanROWFV1RURHNHRDS3M4
            QkxpeFowNkdZSlBIbTNvcHZiSlFIS3Z6UTFjCjhKU2tBTWgxWjNZQUZVNU03bDNo
            T2NNVUZKTWVPNEJrbEhjc05MWXdZVHcKLS0tIEtkT1lYanpIQ1lsejRIS1FuNW5n
            KzNYdmxCOTlDMlZzWTRwOER6Zkw1YkUKAITChxFDbqtc8e4EDZPPw2UQWE5oFQb1
            lD3GgDRraNuaOf5TmroxKGnRZmQSY/L2VxOUV27plU0oP8haoJBEAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T11:35:26Z"
    mac: ENC[AES256_GCM,data:QpBM8p6fj5d27KWGlez7rMCh+Hf7vIZGZRM5aRye7AGEzRFagQEc01t1cCoEqG/zB2kNLQQWPvUn0yFaXJoUZFYx0iSfc8sROZ1CnVxWNtjN+8JjpsSpIbJgblw/PNKAYk543phBetZmGoISwWK2+xdelO7XY2LG0/UzcpMuNQg=,iv:wKFwzeAYJY/JHwyCF83w3Vw9pTiZGYIwJpIpXk5/tC8=,tag:+CvUvi/AMvz3FT2uWDou9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
