apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - apisix.yaml
  - apisix-keycloak-plugin.yaml
  - register-site.yaml
  - tools-secret.yaml
  - api-register-secret.yaml
  - api-register-db.yaml


namespace: tn-don-api
namePrefix: don-api-

images:
  - name: don-api-register
    newName: ghcr.io/developer-overheid-nl/don-api-register
    newTag: 7f4ed11119790f7154de4ac4b723ef988a7369ee
  - name: don-register-site
    newName: ghcr.io/developer-overheid-nl/don-register-site
    newTag: ac8786a13578a2a07e1ca50f1b70ffb30040bbd5
  - name: don-tools-api
    newName: ghcr.io/developer-overheid-nl/don-api-tools
    newTag: dea9f870f88ac8f5eef77b71af605e520d017a83
  - name: don-schema-register
    newName: ghcr.io/developer-overheid-nl/don-schema-register
    newTag: d51738bcd24d7da1df37a52b9cb9686a2fc0bbfb

patches:
  - target:
      kind: HelmRelease
      name: apisix
    patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 1
      - op: replace
        path: /spec/values/ingress/hosts/0/host
        value: api.developer.overheid.nl
      - op: replace
        path: /spec/values/ingress/tls/0/hosts/0
        value: api.developer.overheid.nl
      - op: replace
        path: /spec/values/apisix/admin/ingress/hosts/0/host
        value: api-admin.developer.overheid.nl
      - op: replace
        path: /spec/values/apisix/admin/ingress/tls/0/hosts/0
        value: api-admin.developer.overheid.nl
  - target:
        kind: Ingress
        name: register-site-ing
    patch: |    
      - op: replace
        path: /spec/rules/0/host
        value: apis.developer.overheid.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value: apis.developer.overheid.nl
  - target:
        kind: Ingress
        name: don-schema-register-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: schemas.developer.overheid.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value: schemas.developer.overheid.nl
