apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - apisix.yaml
  - apisix-keycloak-plugin.yaml
  - register-site.yaml
  - tools-secret.yaml
  - api-register-secret.yaml
  - api-register-db.yaml


namespace: tn-don-api
namePrefix: don-api-

images:
  - name: don-api-register
    newName: ghcr.io/developer-overheid-nl/don-api-register
    newTag: 26e491a41af3758e61656786a6c173d578d30744
  - name: don-register-site
    newName: ghcr.io/developer-overheid-nl/don-register-site
    newTag: 4acfee59b9d222d7341f4b816849848421790270
  - name: don-tools-api
    newName: ghcr.io/developer-overheid-nl/don-api-tools
    newTag: 9e13b20c62e7a97480a3527a0e8b3ad422875e55

patches:
  - target:
      kind: HelmRelease
      name: apisix
    patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 1
      - op: replace
        path: /spec/values/ingress/hosts/0/host
        value: api.developer.overheid.nl
      - op: replace
        path: /spec/values/ingress/tls/0/hosts/0
        value: api.developer.overheid.nl
      - op: replace
        path: /spec/values/apisix/admin/ingress/hosts/0/host
        value: api-admin.developer.overheid.nl
      - op: replace
        path: /spec/values/apisix/admin/ingress/tls/0/hosts/0
        value: api-admin.developer.overheid.nl
  - target:
        kind: Ingress
        name: register-site-ing
    patch: |    
      - op: replace
        path: /spec/rules/0/host
        value: apis.developer.overheid.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value: apis.developer.overheid.nl
