apiVersion: v1
data:
    PIWIK_PRO_ACCOUNT_ADDRESS: ENC[AES256_GCM,data:ygnSsZgsWJRoADF4aEr+Sc7idUgCtK5XwdJ/lYZx1PzAYKxi1dtFKa8hF+swkhqY,iv:kndL4UWKq5+HQ6Ygxyz2MpOjvD8PLRPx+Oyp0Ftc0I8=,tag:QTlyyHmOJR+kL1Jsy1EE2g==,type:str]
    PIWIK_PRO_SITE_ID: ENC[AES256_GCM,data:+gYpz87x09OuuSHPyF/H2NRbWsNbhbk2pMTX1JWM3VNjFsuHrZAty4xA03cf4EKa,iv:tacVL4bY6TwlbPRuIqlkvmhhJvbyEDoTX6wiLbuLDLc=,tag:6PNu044wL9vsILG06Ue3Bg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: piwik-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VmFia3ZETElDdVUyRnp1
            aTFjRmlBWDVWNUJWdHA0M3dSbDFSQmNSWjJZCllFWEFlSVV1QjNaeXpSVkhMWkUx
            Y2ZaM1plU09HT2xvTFVvc0NyZzFmSEUKLS0tIDI5ZGswSlgzRjIzekUzeTJHLzlC
            L1p3MEJ4NUFQSlEveXNsVlQ2K3dxMHcKTDvZXbdk1tWXlp0EW87vPlB3BJuCGRtM
            z48izwX66Lyd3pXXzd8oWV3ZxJzmqEoHKuxJeqRe/lvJfUvUNchlxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T18:57:11Z"
    mac: ENC[AES256_GCM,data:fCZuj3iPw2NlZCn/FVXAW0gX8OlRsfMPvEuPvAzIvXO3Txr8YZqXSbkB4fqGn4GOyRESouBwNLLrY5rk/xySjBATfbUmZEcwrdqZ/Y6IbyyuWKm1BtBIUuVCWNRSso6LG2KQNjx7OAbubxb0rbhLLZ9POTR+9ogj5XEOOHo9Ntg=,iv:7DKuzFgRcF6d7if1rAIgqfbbgEqNHIP3uzZUJx81eO8=,tag:J8U6v4clSICCPxgULvAtPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
