apiVersion: v1
data:
    API_ENDPOINT: ENC[AES256_GCM,data:uSxJLo30J0JPVZPU/KbmJu4tvdnwIRX7NMWBisQnEKhvChoky3rb3vYAXr8ECRkAIEfofO1CzZajyCXPrLKtOw==,iv:NjYiBseG5QPDwxTefzL58K4g0mKZuU+iWEgRIlL3qQ4=,tag:rlegRylaGZVyid5NnTb46w==,type:str]
    API_X_API_KEY: ENC[AES256_GCM,data:sa9O+Aq1tUpk2rEeQUeZ/DkCcI6uYm+tbx7+30KbAgud2qOkDMBmeYTfYi8exia6,iv:BoffP/C/+Tqq8R2M36UXjwwKkNSrPV1HsfyVbK12nlc=,tag:ZvvwwpT1aIb12FYmM5c6qg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: register-site-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza0JGallZQURjR2ZReUI4
            ei9wQmZIdm9CdEtuWnRyTldOZ0s5Uk5IYmxjCkZpNWlMa1ViTzF4Q3NFUld0cHpR
            QjhuNW9McW51cnR2ckw1WUpLangvalEKLS0tIFN0eUc2MzhLc1FDT1N2R2UwUmN1
            VDFMTDFyRzNqcy8vME5JSW9qMTJaeE0KsE3JdORbUcxwBcl23vSTdyCkkOva0Sh/
            dj/6qxwEOf3KZxQLsjI2al+OAfsr4ZDzHzWBqsc/wbo59HUwDtS8Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T17:29:51Z"
    mac: ENC[AES256_GCM,data:nIPHvRHgg4ylMXqV7evN7/+pipio/NBCS5BSt/3VcA03B6D855Ax8z9+XVBVLvIeQDMizd1rFgOIwoTwGIRxsc0WQg8Mle2XlKRfaNHNvmJGUV7Y4V6yPFnY2oL5GpRZuKoVuGhLaL6lBDE7Z4NYATvZiT079B3mwQ5V4qSlaZs=,iv:3kazTtsHsK6yYmMgXm3z1JcfdC9rdmxQ52Z39oqMSPo=,tag:cWUG/M5dPAaClXEvHe0/Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
