apiVersion: v1
data:
    API_ENDPOINT: ENC[AES256_GCM,data:nk4unWSPbB4yusjE3MOwYg==,iv:uMyg1pqunQP4i+QB6rSVV5usVx0d8d5JeNlaKlgeW68=,tag:wI+fsxTi3uTQ3O4X5B1ixA==,type:str]
    API_URL: ENC[AES256_GCM,data:2SzI2eLJts4orBVpS0acfuGgYvWU4htM4lxvF9BpY3rjynuiSTd9ioC7s+4=,iv:RDYAvJdA9Du1biNCkazAf4armRkvXFkxNMpU/9uSWzA=,tag:qStzZgxaD2CAnfwRfRZLvQ==,type:str]
    API_X_API_KEY: ENC[AES256_GCM,data:AN95rVVFWEjULprrn21udMAfwMh8XxaeEmePxonEu0lpJQAtAQRVQisbYTSCX+pR,iv:seZBYSOLFoniRYAKJtNW0a1AGsn5+IEO6tqTTd00mSI=,tag:NL8l9a0xmL1Kj4pr157kCw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: register-site-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c1VuVTRiYTlNNTZEcDZn
            bm1xS0wzVWtwRTFkbXFzamVWUWRtclBaZkNFCk52by9oWDZMbzZJTnlocGZDd0ZS
            M3RHRisvRVVKa0MyOXNJMkkrWUVVUEkKLS0tIGhOQ3BJdTBiVjRPMERjaFR4czk1
            ZkFFNEVyV0J2QkF6bXFTWlR1bnJqRWMKco8FNLZbT9dLKPPPhgOR4RHFfNTQLRLr
            YbzQuekrp97wSStFnW+LGtZcmxqeQvuwZyd4/UTEOWMZBhZ1xXeKOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T07:37:47Z"
    mac: ENC[AES256_GCM,data:KBxKJZadyBvOrGg5DGYlXEmQAsHCGjlD8msbjaM8hjRT3XQ0GxSBVBkBzGjCheawjFlAPummY8SuH3KHPP2LVMF50OPWGcJ/plWPPp1nmSsh+HJ+rO+JjtJhb7Sdgx6OAq5qIB9+CoAw1sMCfXUijzCe3H5l6bCvTH2sYbVhcpY=,iv:etySdQ8uWZN5g8wquF9w1uQR3aMBXPy6NlTi0xaRdi4=,tag:91Qw8AYTSCmi7t3Ft0Vw8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
