apiVersion: v1
data:
    ALTCHA_HMAC_KEY: ENC[AES256_GCM,data:hmpQM5irSPvqwrHNnt4zZO4cQX/ow9puUvSqkTr6fYqPLYlHvI8joPgodlExQydHpBERtvPH7H8k+TITnCSBJZUD9GGVd4luk6A8AzEi2dZoLajh3XXdNg==,iv:eO3Z/Wp/FBWeUG3ePrUILrBaAjgezd4vOt8GvtFREjg=,tag:3uwr8wE51jWbpyPoE9GVmQ==,type:str]
    API_ENDPOINT: ENC[AES256_GCM,data:kP0/p58QRCsvkgwIaTjSGw==,iv:hiUSYkdTW5VjlRuujbt60D08IlFhKnUbZ86vA+/eNkA=,tag:4xlP6DgEEUNqA/M/YmDyWw==,type:str]
    API_URL: ENC[AES256_GCM,data:vIUdHZkA+BB/7Xja+hbrrEvmU66G3iV5Z2lBGor2pQq+jvSjSflC+P5f2dQ=,iv:cUzltidbrJaqRNDawGpNF60G1zurTeYuXNmw801Rzok=,tag:7KCWGWhzyoJ1F8Hh9U1osw==,type:str]
    API_X_API_KEY: ENC[AES256_GCM,data:9AC4Nm1QVFjv5xOCKIXWCqi6Y4mpbTPLhw0HunzqhOkZuQ7T27jrVBihI2vYFRnN,iv:nTGY6vuAoEbF8Ri0p8JWVg7oHkrmQ8oq/W3yjjKffTo=,tag:A4BHV0XFl0loeuyxxi+Stg==,type:str]
    TOOLS_ENDPOINT: ENC[AES256_GCM,data:ii2rFq8svGA=,iv:ahJzUVJoXmn64qwDwanRtoL0pMw0kHi3WLcAuPwLEBA=,tag:TLLfvxwZq+DT0dGASulWAw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: register-site-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17uzpswwz9g0frdfy7md5kvlvkcw6pkd9k3k2cad6mfe0zdvcm9pscyzd7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRTI3QnROWFZGWndwNlBX
            bkpxVDY2Z2ppYlM4cmFXaWs0V3JoMENwLzFnCm5vUVRQSWtLWjUvK3VobkQwbnhl
            Z29PVjczR1loWEVGcWVwd0dBOEdMTXcKLS0tIFRwREhIbkxYa3JXM2VXR3JmaGIz
            ejdXUmpLcVdpVE0rcVpHZC9zeEppSUUKeIBLM6oX9+g8iJ74cqXP6pQ4pX6eYnxJ
            8fUINKF7JBNBzRMsk35VDR8SMyTEGUtyHjOp7qkVu4H94qT/bhZKOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T14:19:28Z"
    mac: ENC[AES256_GCM,data:XVKQvrdWccYf7A4JrDuRlqXH+LoRW5gb8SYWdrbgsJjSVQKAeuAWCgXhjoVsCe2/HI9fAfr1l4qnd0Dm+Ih5HBpDnXKwPCUPiGwbjHlEJWbxqNp67lB4nXCg5QjFVbxA6EdNjUB+sDc+vo/gdbfg0TmIPlROuf+IIKobiYqYixs=,iv:YSS6nJpwyMGvv4liyqbZdqrAECXehsVLGjIhkn9N1ZU=,tag:SV1gbNAfrcWIrFSstoAU5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
