apiVersion: v1
data:
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:W9QSlooPs33Kzqiy9kYEzYUUwfF3Bb9N,iv:f14ixTQbyCeF4lGxQOJMbNuFLjrPYNm6bcuLSjOH9k4=,tag:ONjJlwmW+hZmfok9hXSXnw==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:oDUK4A==,iv:/6qWVOjUps+K79uIhLZQdxiGFa7U2eQI51oeMzXTPMs=,tag:/ZrFQhoZK5ujoekYjt7wBg==,type:str]
    AUTH_TOKEN_URL: ENC[AES256_GCM,data:tn/rNeO/GGjgNO+hNJ8G3nKiEUt7x0JbRxHWf9ldJSaokKFwJ/WrEugqC5YpBK0iU0fxZW3B8s85z/PkfoYZcTfKpvKyMImDulaCPX2EgVbIzoGm561eZAzDuR92e1lOSXmqJQ==,iv:0VySnuld+nZLnIFl+LugXubGFCWdhSu+i9+Mrc83ARU=,tag:b9dQINuowlEP+684wpEvew==,type:str]
    PDOK_REGISTER_ENDPOINT: ENC[AES256_GCM,data:WbaNbZ/19+pgga92nPTPPrIMzR7+XWpd7+CDGstzwifIE+5eWyoKvPbKox4AL1/drnsM6tMFBtKrF9kGA5YDUCe+92ORfgwr,iv:7d/8Bi2qGLdFq12EsiNpKJWeXa4HMNRfyQKoCj/g2ck=,tag:dlR3acRYNSueLVGIBvf5dQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tools-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR2R5ejJ2QUhuTUhJcTRn
            NitxaThyK2FtS3Z0VkIyeTN6bHQ2R0hrYjJvCm5UMWFmYkE4QXFwS2tFRWhoWUlU
            NGNjWTJrTjJyWEQ4N3VhdkxIRy83SnMKLS0tIG1zclJac01SeVVkT1kydDc4MnVj
            Nkk3MFhMMG5XZnhRYVlWQ0lZZVNyb0kK0VywpRb40PnOV5xnp6efbCqCJgolYKip
            fqBVGyxLYXodgsUsdsaCfamR9FN+z6n9AWhzAbwZvnzVAX3skCTYXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T17:43:34Z"
    mac: ENC[AES256_GCM,data:j88mrKR6f1bA071uYQrdbWvtd34scOVLD3HpbBbbODoG3u7cleZ5C2O/300kuUtLfE3JNsV6125YfeiUMzrqUFtgD3LbnRHEaoyVwivKwpRJxWJoNYPCUyylpHh80Eg0ntZWER/nCEq4GjAIJLaPMrk+KCJROI8NHAhCKO6tS1U=,iv:IUt3EJxd5PjZE40KTuS3Emy+Nm0hAXh5jvmbAZDrO8U=,tag:AiBNQx4UH36EVkQCUl6YFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
