apiVersion: v1
data:
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:Qw0FfLNGcRUEY80p4BEQo5wp7ToVM7eT,iv:1Hb3m5eoURI6Pnl3EKql5JP8PcZskU9GM97ou8w5G/o=,tag:kxZHFIbwEhogkotbC3zmDg==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:+WhjFWXGSM4ImrpCPLpV8nFXypKFxDy31zoJDTpxTCAfDbTqYo4Zh2D/qTM=,iv:HMPj4cvuUz5JpYDosFELJMOFstMktMe7ikjtHQCqQoE=,tag:+WpcazT1mrCRQguFru2Cpg==,type:str]
    AUTH_TOKEN_URL: ENC[AES256_GCM,data:ydct2R+HVHE7OinETPKeHSzw4ynDNvHbOAgBD8NjIZIgy46BhiKEAIkoKt69SI8i1ZN+lCTggwv0hJkqi3qvjq26BZOeBIXhWZ9MhfBrf4dojvismTcXlP2yohelwNfV24OHGA==,iv:+lQ2ykv+MyP9NdW+LkUzMyiSRbIxHtNc6UWjY6I6Qsc=,tag:Hpdyg1yoQc/jrCzDuMkXYg==,type:str]
    PDOK_REGISTER_ENDPOINT: ENC[AES256_GCM,data:FfdnN4ll80TmLOyIeUuZ8ZtBz1zKHuEIkZ6G7BJE4g5Adb4h0hNCi8asB7rFlwMq1J7L3WjS9OPAOHf/f8MODK1oT+7NABcR,iv:pzAYiOlY1AO59oOf7EYrym1ckF5JotEzxBgTgfzu6xs=,tag:m1PXbx9dk5ATz1r/4kza6g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tools-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L2tML3ZPL2s4ZlF5Nm5E
            bkdCU0hyWU5jaG0zRXNrQ08xU2tlOFNCelQwCmkrTnAyRkdqS3JUM0NOZjRUNDJs
            N1B1ZEtHVHlnUkNtWVZ4aVRjYlVUTkUKLS0tIHc2bEZnQlVIMm9sK0lBcFRnclg1
            SGxFSkw4bmlYOFY1WHM4TkNDWWUzencK45hNulEM9xi879005aSIRNwKqSodCKBG
            ogdna/0/JILEE2sR/vybdL4wS53gAMx3hMYeausgBrISlhQsS09+oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T11:13:49Z"
    mac: ENC[AES256_GCM,data:0nfrCJFOwiWK3jBoU8T54brmZCJZdKiKX2chP51OtzMBSAQ7sDeCIm6yRqQdaCD7VH1tH2iA82BtRxjnWITkupm8BxLPg0d/LSWpvKjCy74mocF+KEJHfinqrFDuN41PtDh6Me0goANnyOARoluTRqUjYByMen2QW2tYJG46AIY=,iv:fJsDOnId1a7Zwdmtqwcre3tqkxFqdthM9k7GWrV0PQg=,tag:4T2jypguR9WrQwVCQeNfKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
