apiVersion: v1
data:
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:E/UhnsE04s/wbhInnmAHmlnXcotRhpHc,iv:mhW7KjmUFJcLCZYc3u+TOizGoOL0ojH5aakAlk8G39o=,tag:vEE0qudIb4oSFDJBhGftiA==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:nDsMRmbrcPUi3iop4+0FilX51KVvafyvPjBP3ZYgOpNU41WWpvOEy7utn9s=,iv:V1I8wJc01psB6DkrJfFYG9TAjHtJXzUIzSglV5rTsA0=,tag:jPR79zSk4MiR3PlmI1Qfeg==,type:str]
    KEYCLOAK_BASE_URL: ENC[AES256_GCM,data:SiDVEDjrG43rhcIIhUsLz1vS+cyZHRMjraWPU/TPmLm1PFEWqPyJr6bLLZo3PgnL,iv:gfSJnMAMT340Bf1EX8FUvzvEkyLcUxDmbVQ3IsGD+fc=,tag:/Uk7c+whhfzI5IPwfRwoVA==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:FthciA==,iv:ztU94QQcc7JM28X93ZyS+8Nn4/3Uq3mj8+ryLFP1SFE=,tag:eSA1SJP1kKXG2Lz5J2kPkQ==,type:str]
    PDOK_REGISTER_ENDPOINT: ENC[AES256_GCM,data:fKo2NrUHPsq3C56eCrvVBVCBkSkp1YIsl5d+eoQjsF5PR9MlT1mB8hJLaqYrNclv666iYddpYaTukzaMtU7i9bPl5vcmjaUW,iv:Xitq/Q6lBJ8g+QPgNm3/P/gNTvRB2zVYhfxCyB/cMwc=,tag:ASeI8LYi33l9WA8x2rlA0A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tools-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lt8huh6hzlcjg749dmptaad2wmssct5v99y8jz9yhd5xt62vcyyqg0z5j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVngxSXRvbUVxdGRkTTVF
            SEVKYVBCSWErNjBGWGFNTUV2RGcrWEdKbDJBCjFVeFBYUFUzMzBuWFpTTlFuYUcx
            OW1kQWEyd2JTMzVTYUp4ZW40S1dvazAKLS0tIGhvbXV2dWZuWVpaQktpVHVMK2N0
            amdwZnZrT20yOGoreHEzUzE3Z2M4aDgK3T1c2QaVNscAbOVWCACqPp0/YcMBFk4T
            cj6uH8I7qf5TxwxRymRlyYwLdL37z+nFg1NtD9EsIY7trS4njzsAyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T13:39:20Z"
    mac: ENC[AES256_GCM,data:+eYG+DObw1uPWpjnQS8sGskn5ybjkh8xXChtcjfYnmf3ynib4iL/nsv7QgTAnDCK9U1jA+sm04VtBzQKjluOOruL4qEPkV2gKot66vQkx8u+FLna9kxqiPQOckd4HwLuRpCxOKg7aNJ8iybos7r1Ziy3k1mKV9dDU/F+PcFIH18=,iv:V3S99U0123fjk00gbTsJKcvbQFAup3LtXOxTYsgZ+Ho=,tag:ZUmoEnPJBKg90eSnPEVEOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
