apiVersion: v1
kind: Secret
metadata:
  name: keycloak-login-secret
type: Opaque
stringData:
  admin-password: "changeme-admin-password"
  admin-user: "don"
  db-host: "localhost"
  db-name: "don"
  db-password: "changeme-db-password"
  db-user: "don"
