apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: tn-don-static
namePrefix: don-static-

commonLabels:
  app: static

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: static.k8s.orb.local
      - op: remove
        path: /spec/tls
      - op: remove
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
