apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      location /.well-known/security.txt {
        return 301 $scheme://www.ncsc.nl/.well-known/security.txt;
      }

      location /api/v0 {
        return 301 $scheme://apis.developer.overheid.nl/api/v0
      }

      location /kennisplatform-apis {
        return 301 $scheme://developer.overheid.nl/communities/kennisplatform-apis
      }

      location ~ ^/apis(/.*)?$ {
        return 301 $scheme://apis.developer.overheid.nl/apis$1;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: set-in-overlay
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: svc
                port:
                  number: 80
  tls:
    - hosts:
        - set-in-overlay
      secretName: static-tls
