apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: tn-don-frontend
namePrefix: don-frontend-

commonLabels:
  app: frontend

images:
  - name: static
    newName: ghcr.io/developer-overheid-nl/don-site
    newTag: 5b6e6b539b5c59375057f613104b475e5113d739

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: developer.overheid.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value: developer.overheid.nl
