apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: tn-don-frontend
namePrefix: don-frontend-

commonLabels:
  app: frontend

images:
  - name: static
    newName: ghcr.io/developer-overheid-nl/don-site
    newTag: 8581e461f4a67344b6de4891def2af4d2a4d2f1d

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: developer.overheid.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value: developer.overheid.nl
