apiVersion: v1
data:
    PIWIK_PRO_ACCOUNT_ADDRESS: ENC[AES256_GCM,data:2jJMJxWyLPqx9mqWRpT0Lxdsqw8qo1qbv3o+KX3wKscHbDJqXb+blwUbrGVVA0cr,iv:jXaBqNNHEgerZ8HnWd7w61BRgR09wyiUy1eigTgCzA0=,tag:9bYELi5D5XVXvfUIMYj4XQ==,type:str]
    PIWIK_PRO_SITE_ID: ENC[AES256_GCM,data:KOMEiEaJnYml2gBszFOtNB92hS4QVCl23bZfpXma/Np1U4MJqlT6PQ+OdxZGdvFV,iv:V6e/w1i6yp1snFcRbfs6ekCjQwUg3uc5nYkjjUI985o=,tag:XE16DYOufWdOOPdGs6KbOg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: piwik-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpl0td68sdh0u5q5dpcdh7dh3w5uzj9n0w3j6028hv0f5hqr2ysqq9mns0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMS2hldjBuUGhKTjNhSldQ
            ZVdreVhHNytPU0xadFJ4UHV2NVVHNFVyY3pJCjl1TGZKVHEyYzlMRmxLYWxvN3ZZ
            d0dXbW5BUzAzczhKT3MvdUF0T3VBR0UKLS0tIGhCY0huMElaZGlLbkNDVEtZZ3pF
            MlRQbDFJU2lNaXhRRjB6UVNHbU9ZUlUKQHXqIV5/DKJL3lO6f+wRcB3JMKOxfxIW
            aSmSCGRP7p6bt3eLt/fxzD7S1KOsFBCgi449UkP/Bay283fa3TPAvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T18:57:45Z"
    mac: ENC[AES256_GCM,data:zRmiXlp4X4sBUUzvTyKD02TSUBRblEs8mci3UaxO2B9n+GQESzG0ko3kmqCEDPdVwNdEihCzJYE9MyK8BRPzolz5w99kBPd9J4ElCch/7hx7p/lAGG0icanvoPTyx2i4hfgDfsoMCiLDjGww/rvgsZP57jXrA2aGXNQTRrk8qFk=,iv:hezWAQWDlOGkMbSAzGHGWVFtp/nZvsWvqKeQwmWi3GM=,tag:u/tAxmzjTsPadolPRNI5OQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
