apiVersion: v1
kind: Secret
metadata:
  name: apisix-secret
type: Opaque
data:
  ADMIN_API_KEY: ENC[]
  ETCD_ROOT_PASSWORD: ENC[]
sops:
  age:
    - recipient:
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        -----END AGE ENCRYPTED FILE-----
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
